class PostProcessor:
    """_summary_
    """
    def __init__(self):
        """_summary_
        """
        pass

    def process_text(self, text):
        """ Post Process the bullet points text completion generated by the custom language model to suit the format of a markdown file

        Args:
            text (str): generated bullet points completion text

        Returns:
            str: post processed text
        """
        #TODO Could be improve by using regular expression!!
        new_text = ""
        for char in text:
            if char == '-': 
                new_text += '- '
            elif char == ' ': 
                new_text += '  '
            else: 
                new_text += char
        return new_text